services:
  stripe:
    image: stripe/stripe-cli
    env_file: ./apps/api/.env
    command: listen --forward-to host.docker.internal:5000/api/v1/payments/webhook --api-key ${STRIPE_SECRET_KEY}
    volumes:
      - ~/.config/stripe:/root/.config/stripe